const haikus = [
  {
    id: 1,
    line1: "An old silent pond",
    line2: "A frog jumps into the pond—",
    line3: "Splash! Silence again.",
    date: "2022-01-01",
    location: "Japan",
  },
  {
    id: 2,
    line1: "The light of a candle",
    line2: "Is transferred to another candle—",
    line3: "Spring twilight",
    date: "2022-01-02",
    location: "China",
  },
  {
    id: 3,
    line1: "Autumn moonlight—",
    line2: "a worm digs silently",
    line3: "into the chestnut.",
    date: "2022-01-03",
    location: "USA",
  },
  {
    id: 4,
    line1: "In the cicada's cry",
    line2: "No sign can foretell",
    line3: "How soon it must die.",
    date: "2022-01-04",
    location: "Australia",
  },
  {
    id: 5,
    line1: "Lightning flash—",
    line2: "what I thought were faces",
    line3: "are plumes of pampas grass.",
    date: "2022-01-05",
    location: "Brazil",
  },
  {
    id: 6,
    line1: "A summer river being crossed",
    line2: "how pleasing",
    line3: "with sandals in my hands!",
    date: "2022-01-06",
    location: "India",
  },
  {
    id: 7,
    line1: "The lamp once out",
    line2: "Cool stars enter",
    line3: "The window frame.",
    date: "2022-01-07",
    location: "France",
  },
  {
    id: 8,
    line1: "From time to time",
    line2: "The clouds give rest",
    line3: "To the moon-beholders.",
    date: "2022-01-08",
    location: "Germany",
  },
  {
    id: 9,
    line1: "The sea darkens",
    line2: "The voices of the wild ducks",
    line3: "Are faintly white.",
    date: "2022-01-09",
    location: "Canada",
  },
  {
    id: 10,
    line1: "The old pond",
    line2: "A frog jumps in—",
    line3: "Plop!",
    date: "2022-01-10",
    location: "Mexico",
  },
];

export default haikus;
